### ISSUE TITLE
memory-eater sources

### ISSUE THREAD

**Issue by stokito** [valentinomiazzo/docker-jvm-memory-test#1]
I found your image https://hub.docker.com/r/valentinomiazzo/memory-eater/ but wanted to change it a little bit for my needs.
Could you please upload it's sources to github?
Thank you in advance

**Comment by valentinomiazzo** [comment]
Sources are in this exact repo. Not sure what do you mean :)
For example this is the java code https://github.com/valentinomiazzo/docker-jvm-memory-test/blob/master/MemoryTest.java

**Comment by stokito** [comment]
No, I mean another your image that is not JVM related. But anyway, I just found alternative docker-stress and pumba so I'll close the ticket
